### ISSUE TITLE
Reset CSS pour storybook

### ISSUE THREAD

**Issue by Eireine** [Eireine/petitpot#5]

**Comment by Jean-Serge** [comment]
Tu peux t'inspirer de ça :

* https://github.com/storybookjs/storybook/issues/8144
* https://storybook.js.org/docs/react/configure/story-rendering#adding-to-head

Tu as plusieurs options :

* mettre le CSS dans un `reset.css` dans public et d'ajouter un tag HTML 
```html
<link rel="stylesheet" type="text/css" href="styles/reset.css">
```

* faire la même chose en référençant un fichier public distant (pas dans ton code)

* appliquer la solution d'import du CSS dans la config Storybook


Quoique tu choisisses il pourrait être bien de la faire aussi pour les fonts.
